<?php
/**
 * Plugin functions.
 *
 * @package UploadFromPhone
 */

declare(strict_types = 1);

namespace UploadFromPhone;

use WP_Post;
use WP_Query;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Registers the upload request post type.
 *
 * The post type is not public and has no admin UI. It exists only so that each
 * upload request gets a URL, a slug to act as the token, and an author.
 *
 * @return void
 */
function register_post_type(): void {
	\register_post_type(
		Upload_Request::POST_TYPE,
		[
			'labels'              => [
				'name'          => _x( 'Upload Requests', 'post type general name', 'upload-from-phone' ),
				'singular_name' => _x( 'Upload Request', 'post type singular name', 'upload-from-phone' ),
			],
			'supports'            => [ 'author' ],
			'rewrite'             => [
				/**
				 * Filters the URL prefix of the upload page.
				 *
				 * @param string $slug URL prefix. Default 'upload'.
				 */
				'slug'       => apply_filters( 'upload_from_phone_rewrite_slug', 'upload' ),
				'with_front' => false,
				'feeds'      => false,
				'pages'      => false,
			],
			'public'              => false,
			'publicly_queryable'  => true,
			'show_ui'             => false,
			'show_in_menu'        => false,
			'show_in_rest'        => false,
			'has_archive'         => false,
			'can_export'          => false,
			'exclude_from_search' => true,
			'delete_with_user'    => true,

			/*
			 * Without this, a site on plain permalinks would address the upload
			 * page as `?post_type=…&p=123` — a guessable post ID standing in for
			 * an unguessable token. With it, the token is in the URL either way.
			 */
			'query_var'           => 'ufph_upload_request',
		]
	);
}

/**
 * Registers the REST API routes.
 *
 * @return void
 */
function register_rest_routes(): void {
	$controller = new REST_Upload_Requests_Controller();
	$controller->register_routes();
}

/**
 * Lets upload requests reach core's media endpoints.
 *
 * Hooked early and unconditionally: the access it grants is decided per
 * request, and only ever while one is being dispatched.
 *
 * @return void
 */
function register_media_endpoint_access(): void {
	( new Media_Endpoint_Access() )->register();
}

/**
 * Registers the plugin's scripts and styles.
 *
 * @return void
 */
function register_assets(): void {
	foreach ( [ 'editor', 'view' ] as $handle ) {
		$asset        = get_asset_meta( $handle );
		$dependencies = $asset['dependencies'];

		/*
		 * The upload page reads the media processing queue off the global
		 * instead of importing it, so that turning client-side processing off
		 * leaves a page that still uploads rather than one that fails to load.
		 * The build cannot see a dependency that is never imported, so when the
		 * queue is in play the script has to be declared by hand.
		 */
		if ( 'view' === $handle && has_client_side_processing() ) {
			$dependencies[] = 'wp-upload-media';
		}

		wp_register_script(
			"upload-from-phone-$handle",
			plugins_url( "build/$handle.js", UPLOAD_FROM_PHONE_FILE ),
			$dependencies,
			$asset['version'],
			[ 'strategy' => 'defer' ]
		);

		wp_set_script_translations( "upload-from-phone-$handle", 'upload-from-phone' );

		wp_register_style(
			"upload-from-phone-$handle",
			plugins_url( "build/$handle.css", UPLOAD_FROM_PHONE_FILE ),
			'editor' === $handle ? [ 'wp-components' ] : [],
			$asset['version']
		);

		wp_style_add_data( "upload-from-phone-$handle", 'rtl', 'replace' );
	}
}

/**
 * Returns the build metadata for a given entry point.
 *
 * @param string $handle Entry point name.
 * @return array{dependencies: string[], version: string} Asset metadata.
 */
function get_asset_meta( string $handle ): array {
	$asset_file = UPLOAD_FROM_PHONE_DIR . "/build/$handle.asset.php";

	/**
	 * Asset metadata as generated by the build.
	 *
	 * @var array{dependencies?: string[], version?: string} $asset
	 */
	$asset = is_readable( $asset_file ) ? require $asset_file : [];

	return [
		'dependencies' => $asset['dependencies'] ?? [],
		'version'      => $asset['version'] ?? VERSION,
	];
}

/**
 * Enqueues the editor integration.
 *
 * @return void
 */
function enqueue_block_editor_assets(): void {
	if ( ! current_user_can( 'upload_files' ) ) {
		return;
	}

	wp_enqueue_script( 'upload-from-phone-editor' );
	wp_enqueue_style( 'upload-from-phone-editor' );
}

/**
 * Determines whether the upload page uses client-side media processing.
 *
 * WordPress ships the whole optimisation pipeline — HEIC conversion, resizing,
 * cropping to the registered image sizes, compression — as `wp-upload-media`,
 * and the upload page routes files through it when the site has it.
 *
 * Core's own switch is checked first, so a site that has turned the feature off
 * has turned it off here too. It also covers the case that matters most on a
 * phone: the pipeline needs `SharedArrayBuffer`, which needs a secure context,
 * so core reports it unavailable on a site that is not served over HTTPS.
 *
 * @return bool Whether to use client-side media processing.
 */
function has_client_side_processing(): bool {
	if ( ! wp_script_is( 'wp-upload-media', 'registered' ) ) {
		return false;
	}

	// Guarded so that a site running below the required version degrades to
	// plain uploads rather than fataling on the way to the file picker.
	if (
		function_exists( 'wp_is_client_side_media_processing_enabled' )
		&& ! wp_is_client_side_media_processing_enabled()
	) {
		return false;
	}

	/**
	 * Filters whether the upload page uses client-side media processing.
	 *
	 * Has no effect where WordPress has it turned off already.
	 *
	 * @param bool $enabled Whether to use client-side media processing. Default true.
	 */
	return (bool) apply_filters( 'upload_from_phone_client_side_processing', true );
}

/**
 * Returns the major version of the requesting Chromium-based browser.
 *
 * Mirrors core's `wp_get_chromium_major_version()`, kept separate so that this
 * file does not depend on a function added in the same release as the feature.
 *
 * @return int|null Major version, or null if the browser is not Chromium-based.
 */
function get_chromium_major_version(): ?int {
	$user_agent = isset( $_SERVER['HTTP_USER_AGENT'] )
		? sanitize_text_field( wp_unslash( $_SERVER['HTTP_USER_AGENT'] ) )
		: '';

	if ( '' === $user_agent ) {
		return null;
	}

	if ( preg_match( '/Chrome\/(\d+)/', $user_agent, $matches ) ) {
		return (int) $matches[1];
	}

	return null;
}

/**
 * Sends the headers that put the upload page in a cross-origin isolated context.
 *
 * The image pipeline runs on wasm-vips, which needs `SharedArrayBuffer`, which
 * browsers only hand out to cross-origin isolated documents. Without these
 * headers the queue still loads, but every operation that would resize, crop,
 * or compress an image quietly reports itself as unsupported and the file goes
 * up untouched.
 *
 * Chromium 137+ gets Document-Isolation-Policy, which isolates this document
 * without imposing anything on the rest of the site, and is what core sends in
 * the editor. Everything else gets the older COOP/COEP pair, which core
 * deliberately does not send in wp-admin: COEP applies to the whole document
 * and breaks plugins that embed cross-origin iframes. This page is ours alone
 * and loads nothing but its own same-origin assets, so the fallback is safe
 * here and gets the pipeline working on considerably more phones.
 *
 * @return void
 */
function send_cross_origin_isolation_headers(): void {
	if ( ! has_client_side_processing() || headers_sent() ) {
		return;
	}

	/**
	 * Filters whether to make the upload page cross-origin isolated.
	 *
	 * Turning this off leaves client-side media processing loaded but unable to
	 * do any image work, so it is only worth doing to debug a conflict.
	 *
	 * @param bool $enabled Whether to send cross-origin isolation headers. Default true.
	 */
	if ( ! apply_filters( 'upload_from_phone_cross_origin_isolation', true ) ) {
		return;
	}

	$chromium_version = get_chromium_major_version();

	if ( null !== $chromium_version && $chromium_version >= 137 ) {
		header( 'Document-Isolation-Policy: isolate-and-credentialless' );

		return;
	}

	header( 'Cross-Origin-Opener-Policy: same-origin' );
	header( 'Cross-Origin-Embedder-Policy: require-corp' );
}

/**
 * Prints the assets the upload page needs, and only those.
 *
 * `wp_head()` would drag in the active theme's stylesheet and every plugin's
 * front-end assets. Whoever opened the link is not there to look at the site,
 * and the page has to behave the same way on every theme, so the plugin's own
 * handles are printed directly instead. Dependencies still resolve normally.
 *
 * @return void
 */
function print_upload_page_assets(): void {
	if ( ! wp_script_is( 'upload-from-phone-view', 'registered' ) ) {
		return;
	}

	wp_styles()->do_items( [ 'upload-from-phone-view' ] );
	wp_scripts()->do_items( [ 'upload-from-phone-view' ] );
}

/**
 * Filters the template used for the upload page.
 *
 * @param string $template Template path.
 * @return string Filtered template path.
 */
function filter_template_include( string $template ): string {
	if ( ! is_singular( Upload_Request::POST_TYPE ) ) {
		return $template;
	}

	$post = get_queried_object();

	/*
	 * WordPress will happily resolve any publicly queryable post by its ID.
	 * The whole security model here rests on the token being unguessable, so a
	 * page reached by a post ID rather than by following the link is a 404 —
	 * otherwise counting upwards from 1 would find every live upload request.
	 */
	if ( ! $post instanceof WP_Post || (string) get_query_var( 'name' ) !== $post->post_name ) {
		global $wp_query;

		if ( $wp_query instanceof WP_Query ) {
			$wp_query->set_404();
		}

		status_header( 404 );
		nocache_headers();

		return get_404_template();
	}

	// A page carrying a live token has no business being indexed or cached.
	if ( ! headers_sent() ) {
		header( 'X-Robots-Tag: noindex, nofollow', true );
	}

	nocache_headers();

	send_cross_origin_isolation_headers();

	/**
	 * Filters the template used to render the upload page.
	 *
	 * @param string $template Absolute path to the template file.
	 */
	return (string) apply_filters(
		'upload_from_phone_template',
		UPLOAD_FROM_PHONE_DIR . '/templates/upload-page.php'
	);
}

/**
 * Returns a list of every registered image size, in the shape the queue wants.
 *
 * Mirrors what WordPress puts on the REST index for the editor. The upload page
 * cannot read that: it is exposed only to users who may upload files, and
 * whoever opened the link is not logged in at all — so the sizes travel with
 * the page instead.
 *
 * @return array Registered image sizes, keyed by size name.
 *
 * @phpstan-return array<string, array<string, mixed>>
 */
function get_all_image_sizes(): array {
	$sizes = wp_get_registered_image_subsizes();

	foreach ( $sizes as $name => &$size ) {
		$size['height'] = (int) $size['height'];
		$size['width']  = (int) $size['width'];
		$size['name']   = $name;
	}
	unset( $size );

	return $sizes;
}

/**
 * Returns the data the upload page needs, ready to be handed to the browser.
 *
 * @param Upload_Request $upload_request The upload request.
 * @return array Upload page data.
 *
 * @phpstan-return array<string, mixed>
 */
function get_upload_page_data( Upload_Request $upload_request ): array {
	$allowed_types = $upload_request->get_allowed_types();
	$mime_types    = get_allowed_mime_types( $upload_request->get_author_id() );

	if ( ! empty( $allowed_types ) ) {
		$mime_types = array_filter(
			$mime_types,
			static function ( string $mime_type ) use ( $allowed_types ): bool {
				return \in_array( explode( '/', $mime_type )[0], $allowed_types, true );
			}
		);
	}

	$data = [
		/*
		 * The upload itself goes over XMLHttpRequest rather than apiFetch, so
		 * that the phone can show how far along a large photo is, which means
		 * the endpoint has to be addressed absolutely.
		 */
		'mediaUrl'          => rest_url( 'wp/v2/media' ),
		'token'             => $upload_request->get_token(),
		'allowedTypes'      => $allowed_types,
		'allowedMimeTypes'  => $mime_types,
		'accept'            => $upload_request->get_accept(),
		'multiple'          => $upload_request->allows_multiple(),
		'maxFiles'          => $upload_request->get_max_files(),
		'maxUploadFileSize' => wp_max_upload_size(),
		'expiresAt'         => $upload_request->get_expires_at(),
		'clientSide'        => has_client_side_processing(),
	];

	if ( ! $data['clientSide'] ) {
		return $data;
	}

	/*
	 * The values the image pipeline needs in order to produce the same files
	 * the server would have. Each is the site's own setting, read through the
	 * same filter the server-side image editor reads it through, so a plugin
	 * that changes one changes it for client-generated images too.
	 */

	/** This filter is documented in wp-admin/includes/image.php */
	$data['bigImageSizeThreshold'] = (int) apply_filters( 'big_image_size_threshold', 2560, [ 0, 0 ], '', 0 ); // phpcs:ignore WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedHooknameFound

	/** This filter is documented in wp-includes/class-wp-image-editor-imagick.php */
	$data['imageStripMeta'] = (bool) apply_filters( 'image_strip_meta', true ); // phpcs:ignore WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedHooknameFound

	/*
	 * On the server this filter receives the decoded image's actual bit depth.
	 * Nothing is decoded server-side on this path, so it is applied with 16 —
	 * the deepest vips will produce — as both the value and the current depth.
	 */
	/** This filter is documented in wp-includes/class-wp-image-editor-imagick.php */
	$data['imageMaxBitDepth'] = (int) apply_filters( 'image_max_bit_depth', 16, 16 ); // phpcs:ignore WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedHooknameFound

	$data['allImageSizes'] = get_all_image_sizes();

	return $data;
}

/**
 * Adds a cron schedule for running every 15 minutes.
 *
 * @param array $schedules Cron schedules.
 * @return array Filtered cron schedules.
 *
 * @phpstan-param array<string, array{interval: int, display: string}> $schedules
 * @phpstan-return array<string, array{interval: int, display: string}>
 */
function filter_cron_schedules( array $schedules ): array {
	if ( ! isset( $schedules['upload_from_phone_quarter_hourly'] ) ) {
		$schedules['upload_from_phone_quarter_hourly'] = [
			'interval' => 15 * MINUTE_IN_SECONDS,
			'display'  => __( 'Every 15 Minutes', 'upload-from-phone' ),
		];
	}

	return $schedules;
}

/**
 * Deletes upload requests that have expired.
 *
 * @return void
 */
function delete_expired_requests(): void {
	$posts = get_posts(
		[
			'post_type'        => Upload_Request::POST_TYPE,
			'post_status'      => 'publish',
			'numberposts'      => 100,
			'suppress_filters' => false,
			'meta_query'       => [ // phpcs:ignore WordPress.DB.SlowDBQuery.slow_db_query_meta_query
				[
					'key'     => Upload_Request::META_EXPIRES_AT,
					'value'   => time(),
					'compare' => '<=',
					'type'    => 'NUMERIC',
				],
			],
		]
	);

	foreach ( $posts as $post ) {
		$upload_request = Upload_Request::from_post( $post );

		if ( $upload_request instanceof Upload_Request ) {
			$upload_request->delete();
		}
	}
}

/**
 * Plugin activation hook.
 *
 * @codeCoverageIgnore
 *
 * @return void
 */
function activate_plugin(): void {
	register_post_type();

	flush_rewrite_rules( false );

	if ( false === wp_next_scheduled( 'upload_from_phone_cleanup' ) ) {
		wp_schedule_event( time(), 'upload_from_phone_quarter_hourly', 'upload_from_phone_cleanup' );
	}
}

/**
 * Plugin deactivation hook.
 *
 * @codeCoverageIgnore
 *
 * @return void
 */
function deactivate_plugin(): void {
	delete_expired_requests();

	unregister_post_type( Upload_Request::POST_TYPE );

	flush_rewrite_rules( false );

	$timestamp = wp_next_scheduled( 'upload_from_phone_cleanup' );

	if ( false !== $timestamp ) {
		wp_unschedule_event( $timestamp, 'upload_from_phone_cleanup' );
	}
}
